//Daniel Marquez wuz here *rock hands*
//Derived from Team 303's code.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import com.ctre.phoenix.music.Orchestra;
import com.ctre.phoenix.motorcontrol.can.TalonFX;
import java.util.ArrayList;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class Jukebox extends SubsystemBase {
    
    //Music Control Variables
    boolean shouldPlay = true;
    int delay = 3600;

    Orchestra orchestra; //Orchestra class
    TalonFX[] motors = {new TalonFX(1), new TalonFX(2)}; //Add the motorIDs that will play the song
    String songToPlay = "Wii-Song.chrp"; //Load any song filename found in src\main\deploy - .chrp files generated by phoenix tuner

    //Initialize method called by RobotContainer
    public void startJukebox() {
        ArrayList<TalonFX> instruments = new ArrayList<TalonFX>(); //Create Arraylist of instruments to pass to orchestra
        //Add each motor to the list - technically you could skip this whole step but shush
        for(TalonFX motor : motors) {
            instruments.add(motor);
        }
        orchestra = new Orchestra(instruments); //Define Orchestra with motorIDs
        orchestra.loadMusic(songToPlay); //Load specified song filename
        SmartDashboard.putBoolean("Play Music?", true); //Create variable that can be changed at runtime by FRC Driver Station
        
    }

    @Override
    public void periodic() {
        //Check status of driver station variable, return false if no variable found
        boolean playMusic = SmartDashboard.getBoolean("Play Music?", false);

        //Play or Stop music depending on variable status
        if(playMusic && shouldPlay && delay >= 0) {
            orchestra.play();
            delay--;
        }
        else {
            orchestra.stop();
            delay = 3600;
        }
    }

}
